package Vistas;

import Clases.Alumno;
import Clases.Materia;
import java.util.HashSet;

public class MenuPrincipal extends javax.swing.JFrame {

    public static final HashSet<Alumno> listaAlumnos = new HashSet<>();
    public static final HashSet<Materia> listaMaterias = new HashSet<>();

    public MenuPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        setSize(800, 600);
        
        inicializarValores();

    }

    private void inicializarValores() {
        //a) Crear las materias://
        listaMaterias.add(new Materia(1, "Ingles I", 1));
        listaMaterias.add(new Materia(2, "Matematica I", 1));
        listaMaterias.add(new Materia(3, "Laboratorio I", 1));
        
        //b) Crear 2 alumnos://        
        listaAlumnos.add(new Alumno(1001, "Lopez", "Martin"));
        listaAlumnos.add(new Alumno(1002, "Martinez", "Brenda"));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jAlumno = new javax.swing.JMenu();
        jAgregarAlumno = new javax.swing.JMenuItem();
        jMateria = new javax.swing.JMenu();
        jAgregarMateria = new javax.swing.JMenuItem();
        jRegistro = new javax.swing.JMenu();
        jInscripcion = new javax.swing.JMenuItem();
        jSalir = new javax.swing.JMenu();
        jSalida = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setBackground(new java.awt.Color(153, 0, 255));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
        );

        jAlumno.setText("Alumno");

        jAgregarAlumno.setText("Agregar Alumno");
        jAgregarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAgregarAlumnoActionPerformed(evt);
            }
        });
        jAlumno.add(jAgregarAlumno);

        jMenuBar1.add(jAlumno);

        jMateria.setText("Materia");

        jAgregarMateria.setText("Agregar Materia");
        jAgregarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAgregarMateriaActionPerformed(evt);
            }
        });
        jMateria.add(jAgregarMateria);

        jMenuBar1.add(jMateria);

        jRegistro.setText("Registro");
        jRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegistroActionPerformed(evt);
            }
        });

        jInscripcion.setText("Inscripcion");
        jInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInscripcionActionPerformed(evt);
            }
        });
        jRegistro.add(jInscripcion);

        jMenuBar1.add(jRegistro);

        jSalir.setText("Salir");
        jSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalirActionPerformed(evt);
            }
        });

        jSalida.setText("Salida");
        jSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalidaActionPerformed(evt);
            }
        });
        jSalir.add(jSalida);

        jMenuBar1.add(jSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAgregarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAgregarAlumnoActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        AlumnosVista agregar = new AlumnosVista();

        agregar.setVisible(true);
        agregar.setSize(800, 577);
        escritorio.add(agregar);
        escritorio.repaint();
        escritorio.moveToFront(agregar);
    }//GEN-LAST:event_jAgregarAlumnoActionPerformed

    private void jAgregarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAgregarMateriaActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        MateriasVista agregar = new MateriasVista();
        agregar.setVisible(true);
        escritorio.add(agregar);
        escritorio.repaint();
        escritorio.moveToFront(agregar);
    }//GEN-LAST:event_jAgregarMateriaActionPerformed

    private void jInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInscripcionActionPerformed
        escritorio.removeAll();
        InscripcionesVista agregar = new InscripcionesVista();
        agregar.setVisible(true);
        escritorio.add(agregar);
        escritorio.repaint();
        escritorio.moveToFront(agregar);        // TODO add your handling code here:
    }//GEN-LAST:event_jInscripcionActionPerformed

    private void jRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRegistroActionPerformed

    private void jSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalidaActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jSalidaActionPerformed

    private void jSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalirActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_jSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem jAgregarAlumno;
    private javax.swing.JMenuItem jAgregarMateria;
    private javax.swing.JMenu jAlumno;
    private javax.swing.JMenuItem jInscripcion;
    private javax.swing.JMenu jMateria;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jRegistro;
    private javax.swing.JMenuItem jSalida;
    private javax.swing.JMenu jSalir;
    // End of variables declaration//GEN-END:variables
}
